apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 153278745791.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 153278745791.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: abcdefg
- name: 153278745791.dkr.ecr.ap-northeast-2.amazonaws.com/test-mphong-demo-frontend
  newName: 153278745791.dkr.ecr.ap-northeast-2.amazonaws.com/test-mphong-demo-frontend
  newTag: "59362534"
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
